### ISSUE TITLE
How should this package be pronounced phonetically?

### ISSUE THREAD

**Issue by jhowardjr** [jhowardjr/variadic.js#1]
The name of the package is just anagram of variadic. Need some advice on how the package should be pronounced?

**Comment by ignacioxd** [comment]
Maybe the package should really be called "variadic" to improve its discoverability.

If you still prefer the anagram idea, maybe instead of just the word "variadic" in reverse you can use a different anagram, such as "ricavida" or "vidarica", etc.

**Comment by jhowardjr** [comment]
+1 vidarica. I actually wanted variadic, but it looks like someone already has it [variadic](https://www.npmjs.com/package/variadic). We could reach and see if the owner is willing to relinquish the name.

**Comment by jhowardjr** [comment]
Good news! We were able to procure the variadic.js npm name. The developer was more than happy to let us take ownership. The package can now be found at https://www.npmjs.com/package/variadic.js
