### ISSUE TITLE
Adopt an automated coding style

### ISSUE THREAD

**Issue by jhowardjr** [jhowardjr/variadic.js#17]
Help to enforce a style guide using existing style guides.

**Comment by scottwestover** [comment]
For this, are you thinking of something like eslint and https://github.com/airbnb/javascript ?

**Comment by scottwestover** [comment]
I started working on adding eslint to our code. There is a new branch called eslint that shows what I have worked on.

**Comment by jhowardjr** [comment]
Exactly! Good find!

**Comment by jhowardjr** [comment]
@scottwestover so after running ```--fix``` with the linter I think we can easily address the remaining issues. The only rule I think we should exclude is the ``` iterators/generators ...``` finding. There's a whole dialogue about this rule here https://github.com/airbnb/javascript/issues/1122. Within the scope of this class, the for...of seems legit for our use, but if someone wants to use arrays iterations I think that's ok too.
